# Generated by Django 2.2.5 on 2019-09-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190909_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='caption',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_done_by',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_giver',
            field=models.CharField(max_length=30),
        ),
    ]
